# Generated by Django 2.0.8 on 2018-09-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180926_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='thought',
            new_name='content',
        ),
    ]
